FRONT-6558 add onlyUseSummaries and createSummaries flags to TimeseriesQuery
scalyr/Scalyr-Java-Client pull request #54
Opened 2021-12-07 20:22 UTC by stuart-gill

2022-01-06 00:21 UTC, stuart-gill commented
https://scalyr.myjetbrains.com/youtrack/issue/FRONT-6558

2022-01-06 18:50 UTC, jjhart requested changes
Some ideas about comments.

High level question: when I issue a query that sets `onlyUseSummaries=true`, how do we reflect to the user whether or not the query results are complete?

Let's say I've backfilled 1 week, and then I issue a `[2w->now]` query with 14 buckets.  Does our API simply show the first 7 buckets are 0, or do we also communicate "these results are only valid from $DATE" or even just "these results are incomplete".

The backend communicates this in the `QueryResult.eventDatabaseNeeded` field, but we should also propagate that through the API response and also through this client library.

2022-01-06 18:50 UTC, jjhart commented on src/main/com/scalyr/api/query/QueryService.java
> +   * Retrieve numeric data from one or more timeseries, automatically creating them as a side effect if necessary, unless
We can further simplify, I think.

```
Execute one or more numeric queries, optionally creating timeseries for them if `createTimeseries` is true.
A timeseries precomputes a ...
```

2022-01-06 18:50 UTC, jjhart commented on src/main/com/scalyr/api/query/QueryService.java
> +   * begin a background process to backpropagate the timeseries over data we have already received.  The result is that,
This paragraph is no longer perfectly true, as we only backfill data as far back as you've asked (rather than "always backfill for all time", which is expensive).

_maybe something like this_

When a new timeseries is defined, we immediately start live updating of that timeseries from the ingestion pipeline.  In addition, we begin a background process to extend the timeseries backward in time, so that it covers the full timespan of your query.  This backfill process is automatic, and if you later issue the same query with an even earlier start time, we will extend the backfill to cover that as well.

To change this behavior, set `createSummaries` to false.

A related flag, `onlyUseSummaries`, controls whether _this_ API call should only use preexisting timeseries or should actually execute the queries against the event database.  If set to true, then your API call is guaranteed to return quickly and to execute inexpensively, but with possibly-incomplete results.  If set to false, the call slower & more expensive, but will be complete.

Issuing a new query over the past 3 weeks with `createSummaries = true, onlyUseSummaries = true` will return quickly no matter what, but will initially return incomplete results until backfill (covering the past 3 weeks) is complete.  This can be a cost-effective way to seed a new timeseries with a long backfill period when you don't need complete results right away.

Issuing a query with `createSummaries = false, onlyUseSummaries = false` is equivalent to a {@link numericQuery} call.

2022-01-06 23:45 UTC, stuart-gill commented
Thanks for the notes on the Javadoc! I made and pushed those changes. 

I think that if the fastpath failed and onlyUseSummaries is true, then we return an empty values array and the message "Waiting for summary data to be populated". [Here](https://github.com/scalyr/scalyr/blob/546bd55e13e8bc7b52d79eb68e11b5e775dc5f5a/ScalyrSite/src/logs/api/TimeseriesQueryApiHandler.java#L258) is that response in the API. And the [fastpath fails if ANY bucket isn't populated](https://github.com/scalyr/scalyr/blob/546bd55e13e8bc7b52d79eb68e11b5e775dc5f5a/ScalyrSite/src/web/scalyr/events/ui/NumericQueryManager.java#L809), unless I'm mistaken. 

But you're right, I didn't handle this case in the Java Client. I just fixed that and pushed the changes, so that the message returned by the API ("Waiting for summary data to be populated") is passed through the Java Client

2022-01-07 00:15 UTC, jjhart approved these changes
This looks great.  Thank you for providing those links, I appreciate it!

2022-01-07 00:36 UTC, merged